# Generated by Django 5.2.7 on 2025-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
