# Generated by Django 5.2.7 on 2025-12-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0003_donation_payment_intent_donation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Support Us', max_length=100)),
                ('qr_image', models.ImageField(upload_to='donate/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
